//
//  MonthlyReport.swift
//  agile-self
//
//  Created by Claude on 2026/02/22.
//

import Foundation
import SwiftData

// MARK: - Supporting Types (must be top-level, not nested inside @Model)

/// A correlation between two tracked factors discovered by on-device AI analysis.
nonisolated struct Correlation: Codable, Identifiable, Sendable {
    var id: UUID
    /// First factor name (e.g. "Sleep").
    var factor1: String
    /// Second factor name (e.g. "Focus").
    var factor2: String
    /// Pearson correlation coefficient, range -1.0 to 1.0.
    var coefficient: Double
    /// Human-readable description of the relationship (e.g. "Sleep^ = Focus^").
    var description: String

    init(
        id: UUID = UUID(),
        factor1: String,
        factor2: String,
        coefficient: Double,
        description: String
    ) {
        self.id = id
        self.factor1 = factor1
        self.factor2 = factor2
        self.coefficient = coefficient
        self.description = description
    }
}

// MARK: - MonthlyReport Model

/// An AI-generated monthly report summarising check-in trends, health data, and discovered correlations.
@Model
final class MonthlyReport {

    // MARK: - Persisted Properties

    @Attribute(.unique) var id: UUID
    /// Calendar month (1-12).
    var month: Int
    /// Calendar year (e.g. 2026).
    var year: Int
    /// AI-generated executive summary of the month.
    var executiveSummary: String?
    /// The single most impactful insight for the month.
    var topInsight: String?
    /// Average composite score across all daily check-ins in the month.
    var overallScore: Double?
    /// JSON-encoded array of Correlation structs.
    var correlationsJSON: Data?
    /// Whether the report has been generated by AI.
    var isGenerated: Bool
    var createdAt: Date
    /// Timestamp when the report was generated.
    var generatedAt: Date?

    // MARK: - Initialization

    init(
        id: UUID = UUID(),
        month: Int,
        year: Int,
        executiveSummary: String? = nil,
        topInsight: String? = nil,
        overallScore: Double? = nil,
        correlationsJSON: Data? = nil,
        isGenerated: Bool = false,
        createdAt: Date = Date(),
        generatedAt: Date? = nil
    ) {
        self.id = id
        self.month = month
        self.year = year
        self.executiveSummary = executiveSummary
        self.topInsight = topInsight
        self.overallScore = overallScore
        self.correlationsJSON = correlationsJSON
        self.isGenerated = isGenerated
        self.createdAt = createdAt
        self.generatedAt = generatedAt
    }

    // MARK: - Correlation Helpers

    /// Decodes the correlations from JSON. Returns an empty array on failure.
    var correlations: [Correlation] {
        guard let data = correlationsJSON else { return [] }
        return (try? JSONDecoder().decode([Correlation].self, from: data)) ?? []
    }

    /// Encodes and persists the correlations as JSON.
    func setCorrelations(_ correlations: [Correlation]) {
        correlationsJSON = try? JSONEncoder().encode(correlations)
    }
}
